// lib/properties.ts
export type PropertyStatus = "For Sale" | "For Rent";

export interface Property {
  id: string;
  title: string;
  city: string;
  location: string;
  price: number;
  beds: number;
  baths: number;
  area: number;
  status: PropertyStatus;
  type: string; // Added: Villa, Apartment, Penthouse, etc.
  tags: string[]; // Added: For search filtering
  image: string;
  description: string;
  features: string[];
}

export const properties: Property[] = [
  {
    id: "docnah-studio-28",
    title: "Luxury Studio Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Century Mall",
    price: 3220000,
    beds: 0,
    baths: 1,
    area: 28,
    status: "For Sale",
    type: "Studio",
    tags: ["luxury", "investment", "smart home", "gym", "spa"],
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    description:
      "Modern studio apartment in Trend Park Residence, Megenagna. Features premium high-rise living with access to gym, spa, car elevators, and 24/7 security.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Children Playground",
      "24/7 Security",
      "Car Elevator",
      "EV Charging Station",
      "Backup Generator",
    ],
  },
  {
    id: "docnah-1bed-42",
    title: "1 Bedroom Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Century Mall",
    price: 4830000,
    beds: 1,
    baths: 1,
    area: 42,
    status: "For Sale",
    type: "Apartment",
    tags: ["luxury", "new build", "balcony", "city view"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    description:
      "Elegant 1-bedroom unit at Trend Park Residence (B+G+23). Features contemporary finishes, flexible 15% down payment option, and world-class building amenities.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Commercial Supermarket",
      "Adequate Parking",
      "24/7 Security",
      "Elevators",
    ],
  },
  {
    id: "docnah-2bed-70",
    title: "Spacious 2 Bedroom Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Century Mall",
    price: 8050000,
    beds: 2,
    baths: 2,
    area: 70,
    status: "For Sale",
    type: "Apartment",
    tags: ["family", "luxury", "discount available", "prime location"],
    image:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    description:
      "Spacious 2-bedroom luxury apartment located in prime Megenagna. Offers stunning panoramic city views, modern layout, and full access to building facilities.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Cafe & Restaurant",
      "Children Playground",
      "Car Elevator",
      "Reception & Security",
    ],
  },
  {
    id: "docnah-2bed-101",
    title: "Premium 2 Bedroom Unit - Trend Park Residence",
    city: "Addis Ababa",
    location: "Megenagna, Near Century Mall",
    price: 11643750,
    beds: 2,
    baths: 2,
    area: 101,
    status: "For Sale",
    type: "Apartment",
    tags: ["luxury", "spacious", "high floor", "smart payment"],
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    description:
      "Generously sized 101.25 sqm 2-bedroom residence with premium layout and high quality finishes. Special promotional pricing and flexible payment terms available.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Supermarket",
      "EV Charging",
      "24/7 Security",
      "Backup Generator",
    ],
  },
  {
    id: "docnah-3bed-140",
    title: "Executive 3 Bedroom Residence in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Century Mall",
    price: 16100000,
    beds: 3,
    baths: 3,
    area: 140,
    status: "For Sale",
    type: "Penthouse",
    tags: ["luxury", "spacious", "family home", "panoramic view"],
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    description:
      "Expansive 3-bedroom luxury residence on high floors offering maximum comfort, modern design, master suite, and access to all luxury amenities in Megenagna.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Daycare & Playground",
      "Car Elevator",
      "Commercial Mall & Cafe",
      "24/7 Security",
    ],
  },
  {
    id: "docnah-studio-22",
    title: "Compact Studio Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 2546100,
    beds: 0,
    baths: 1,
    area: 22,
    status: "For Sale",
    type: "Studio",
    tags: ["studio", "affordable", "investment", "gym", "spa"],
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    description:
      "Modern compact studio apartment located in prime Megenagna. Excellent investment opportunity with low initial down payment options and access to premium building amenities.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Car Elevator",
      "EV Charging Station",
      "Backup Generator",
      "24/7 Security",
    ],
  },
  {
    id: "docnah-1bed-47",
    title: "1 Bedroom Luxury Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 5462500,
    beds: 1,
    baths: 1,
    area: 47,
    status: "For Sale",
    type: "Apartment",
    tags: ["1 bedroom", "luxury", "discount available", "balcony"],
    image:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    description:
      "Well-planned 1-bedroom residence offering modern finishes, large windows, and access to all amenities including pool, gym, and commercial areas.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Cafe & Restaurant",
      "Children Playground",
      "EV Charging Station",
      "Reception",
    ],
  },
  {
    id: "docnah-2bed-60",
    title: "2 Bedroom Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 6931050,
    beds: 2,
    baths: 2,
    area: 60,
    status: "For Sale",
    type: "Apartment",
    tags: ["2 bedrooms", "family", "prime location", "smart home"],
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    description:
      "Spacious 60.27 sqm 2-bedroom home in Megenagna. Designed for modern family living with high-end safety features, parking, and leisure facilities.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Car Elevator",
      "24/7 Security",
      "Children Playground",
      "Backup Generator",
    ],
  },
  {
    id: "docnah-shop-45",
    title: "Commercial Shop Space in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 4657500,
    beds: 0,
    baths: 1,
    area: 45,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "shop", "high foot traffic", "investment"],
    image:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    description:
      "Prime 45 sqm commercial retail space located on the ground/lower floors of Trend Park Residence. High foot traffic location ideal for shops, cafes, or service centers.",
    features: [
      "High Foot Traffic",
      "Commercial Mall Area",
      "Adequate Parking",
      "24/7 Security",
      "Backup Generator",
    ],
  },
  {
    id: "docnah-1bed-29",
    title: "Modern 1 Bedroom Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 2337984,
    beds: 1,
    baths: 1,
    area: 30,
    status: "For Sale",
    type: "Apartment",
    tags: ["1 bedroom", "city view", "smart home", "discount"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    description:
      "Efficient 1-bedroom home designed for urban living. Conveniently situated in front of Misrak Sub-City with fast access to transport and commercial centers.",
    features: [
      "Swimming Pool",
      "Gym & Spa",
      "Daycare Center",
      "Cafe & Restaurant",
      "Security System",
    ],
  },
  {
    id: "docnah-commercial-45",
    title: "Prime Commercial Retail Shop Space",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 4657500,
    beds: 0,
    baths: 1,
    area: 45,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "shop", "high traffic", "investment"],
    image:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    description:
      "Ground floor commercial store space located in a high-foot-traffic plaza in Megenagna. Ideal for retail stores, boutique offices, or service centers.",
    features: [
      "High Foot Traffic",
      "Plaza Access",
      "Customer Parking",
      "24/7 Security Patrol",
      "Backup Generator",
    ],
  },
  {
    id: "docnah-1bed-31",
    title: "1 Bedroom Residential Apartment in Megenagna",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 4200000,
    beds: 1,
    baths: 1,
    area: 31,
    status: "For Sale",
    type: "Apartment",
    tags: ["1 bedroom", "city view", "modern", "megenagna"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    description:
      "Well-designed 1-bedroom apartment featuring modern layout, flexible payment structure (starting at 10% down payment), and full utility access.",
    features: [
      "Balcony",
      "Underground Parking",
      "High-Speed Elevators",
      "Standby Generator",
    ],
  },
  {
    id: "docnah-commercial-13",
    title: "Prime Commercial Retail Shop / Office Space",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 1300000,
    beds: 0,
    baths: 1,
    area: 13,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "shop", "office", "high traffic"],
    image:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    description:
      "Ideal commercial shop or office space located in a high-foot-traffic plaza in Megenagna. Available for purchase or rent.",
    features: [
      "High Foot Traffic",
      "Plaza Mall Access",
      "Customer Parking",
      "24/7 Security",
    ],
  },
  {
    id: "docnah-comm-13",
    title: "Commercial Office & Retail Shop Space",
    city: "Addis Ababa",
    location: "Megenagna, Near Glass Tower",
    price: 1300000,
    beds: 0,
    baths: 1,
    area: 13,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "office", "retail", "megenagna", "trend residence"],
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    description:
      "Commercial unit inside a B+G+23 Residence Mall with 50% construction progress. Ideal for retail, office, or investment.",
    features: [
      "B+G+23 Mall Complex",
      "Prime Main Road Access",
      "High Foot Traffic",
      "Flexible Layout",
    ],
  },
  {
    id: "docnah-1bed-30",
    title: "1 Bedroom Apartment at Trend Residence",
    city: "Addis Ababa",
    location: "Megenagna, Signal",
    price: 2400000,
    beds: 1,
    baths: 1,
    area: 30,
    status: "For Sale",
    type: "Apartment",
    tags: ["1 bedroom", "megenagna", "discount", "cash deal"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    description:
      "Well-located 1-bedroom unit with 90,000 ETB/sqm pricing and up to 20% discount for full upfront cash payment.",
    features: [
      "City Skyline Views",
      "24/7 Security",
      "Electric Charge Station",
      "Underground Parking",
    ],
  },
  {
    id: "summer-2bed-138",
    title: "Grand Palace View 2 Bedroom Apartment",
    city: "Addis Ababa",
    location: "Near British Embassy",
    price: 10764000,
    beds: 2,
    baths: 2,
    area: 138,
    status: "For Sale",
    type: "Apartment",
    tags: ["british embassy", "grand palace view", "bank loan", "discount"],
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    description:
      "Expansive 138 sqm 2-bedroom residence overlooking the Grand Palace area. Offers 50% bank loan support, 10% down payment option, and holiday promotional discounts.",
    features: [
      "50% Bank Loan Approved",
      "Grand Palace View",
      "Balcony",
      "2 Year Delivery Plan",
    ],
  },
  {
    id: "docnah-1",
    title: "Commercial Shop / Office Space at Megenagna",
    city: "Addis Ababa",
    location: "Megenagna",
    price: 1300000,
    beds: 0,
    baths: 1,
    area: 13,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "shop", "office", "megenagna", "investment"],
    image: "1001616962_2.png",
    description:
      "Commercial shop and office space starting from 13 m² in Megenagna with a flexible 10% down payment plan.",
    features: [
      "10% Down Payment",
      "Flexible Payment Terms",
      "Prime Commercial Location",
      "High Foot Traffic",
    ],
  },
  {
    id: "docnah-2",
    title: "Easter Special Apartment at Central Megenagna",
    city: "Addis Ababa",
    location: "Central Megenagna",
    price: 1600000,
    beds: 1,
    baths: 1,
    area: 22,
    status: "For Sale",
    type: "Apartment",
    tags: ["apartment", "megenagna", "easter promo", "residential"],
    image: "1001616961_2.png",
    description:
      "Special Easter offer for residential units ranging from 22 m² to 140 m² with a full payment start price of 1.6 Million ETB or 10% down payment.",
    features: [
      "10% Down Payment",
      "Multiple Layout Options",
      "Commercial Shops Available",
      "Prime Location",
    ],
  },
  {
    id: "docnah-3",
    title: "Luxury Modern Apartments & Shops at Megenagna",
    city: "Addis Ababa",
    location: "Megenagna",
    price: 1200000,
    beds: 1,
    baths: 1,
    area: 25,
    status: "For Sale",
    type: "Apartment",
    tags: ["apartment", "shop", "megenagna", "luxury"],
    image: "1001616960_2.png",
    description:
      "Shops available from 1.2M ETB, Studio units at 2M ETB, 1-bed at 4M ETB, 2-bed at 6M ETB, and 3-bed at 9M ETB with a 40% initial deposit.",
    features: [
      "40% Down Payment",
      "Elevator",
      "24/7 Security",
      "Mixed Commercial & Residential",
    ],
  },
  {
    id: "docnah-4",
    title: "Prime Commercial Retail Shop at Megenagna",
    city: "Addis Ababa",
    location: "Megenagna",
    price: 1200000,
    beds: 0,
    baths: 1,
    area: 13,
    status: "For Sale",
    type: "Commercial",
    tags: ["shop", "retail", "megenagna", "commercial"],
    image: "1001616959_2.png",
    description:
      "Commercial retail shop space starting from 13 m² priced at 95,000 ETB per square meter in central Megenagna.",
    features: ["95,000 ETB/m²", "High Commercial Value", "Prime Street Access"],
  },
  {
    id: "docnah-5",
    title: "Trend Residence Mall Commercial Offices",
    city: "Addis Ababa",
    location: "Megenagna Signal, near Tamres Building",
    price: 1500000,
    beds: 0,
    baths: 1,
    area: 13,
    status: "For Sale",
    type: "Commercial",
    tags: ["office", "commercial", "signal", "b+g+23"],
    image: "1001616958_2.png",
    description:
      "Commercial office space for rent or sale starting from 13 m² inside the B+G+23 Trend Residence Mall (50% construction completed).",
    features: [
      "B+G+23 Structure",
      "50% Construction Complete",
      "Atrium Interior Design",
      "Parking Facilities",
    ],
  },
  {
    id: "docnah-6",
    title: "High-End Residential Residence at Signal",
    city: "Addis Ababa",
    location: "Megenagna Signal",
    price: 9000000,
    beds: 3,
    baths: 2,
    area: 100,
    status: "For Sale",
    type: "Apartment",
    tags: ["luxury", "apartment", "gym", "spa", "library"],
    image: "1001616957_2.png",
    description:
      "Luxury residential development offering studio to 3-bedroom options at 90,000 ETB per m² with top-tier modern amenities.",
    features: [
      "Private Gym & Spa",
      "Library",
      "Electric Vehicle Charge Station",
      "Retail Mall Access",
      "90,000 ETB/m²",
    ],
  },
  {
    id: "docnah-7",
    title: "Affordable Modern Residential Apartment",
    city: "Addis Ababa",
    location: "Megenagna",
    price: 2000000,
    beds: 1,
    baths: 1,
    area: 30,
    status: "For Sale",
    type: "Apartment",
    tags: ["affordable", "apartment", "low deposit", "megenagna"],
    image: "1001616956_2.png",
    description:
      "Residential apartments starting at 2 Million ETB total price with a low 10% down payment option (200,000 ETB initial payment).",
    features: [
      "10% Down Payment (200,000 ETB)",
      "Studio, 1-3 Bed Units",
      "Modern Interior Architecture",
    ],
  },
  {
    id: "docnah-8",
    title: "Docnah Mixed-Use Tower Units",
    city: "Addis Ababa",
    location: "Megenagna Signal",
    price: 2850000,
    beds: 2,
    baths: 1,
    area: 30,
    status: "For Sale",
    type: "Apartment",
    tags: ["mixed-use", "apartment", "office", "signal"],
    image: "1001616955_2.png",
    description:
      "Residential apartments and finished commercial offices at 95,000 ETB/m² with a 30% initial deposit.",
    features: [
      "30% Down Payment",
      "95,000 ETB/m² Rate",
      "Completed Commercial Spaces",
      "Balconies",
    ],
  },
  {
    id: "docnah-9",
    title: "Mid-Rise Residential & Commercial Tower",
    city: "Addis Ababa",
    location: "Central Megenagna",
    price: 4500000,
    beds: 2,
    baths: 2,
    area: 50,
    status: "For Sale",
    type: "Apartment",
    tags: ["discount", "50% completed", "megenagna", "apartment"],
    image: "1001616954_2.png",
    description:
      "Building at 50% construction completion offering units at 90,000 ETB/m² with 10% down payment and a 20% discount for full 100% upfront payment.",
    features: [
      "20% Full Payment Discount",
      "10% Down Payment Plan",
      "90,000 ETB/m² Rate",
      "50% Construction Stage",
    ],
  },
  {
    id: "docnah-10",
    title: "Compact Studio & Family Apartments",
    city: "Addis Ababa",
    location: "Central Megenagna",
    price: 1700000,
    beds: 1,
    baths: 1,
    area: 25,
    status: "For Sale",
    type: "Apartment",
    tags: ["studio", "1-bed", "2-bed", "3-bed", "full-payment"],
    image: "1001616953_2.png",
    description:
      "Full payment special prices: Studio for 1.7M ETB, 1-bedroom for 2.4M ETB, 2-bedroom for 4.8M ETB, and 3-bedroom for 9.2M ETB.",
    features: [
      "Full Payment Discount Pricing",
      "Shops Available for Rent & Sale",
      "Prime Transit Connectivity",
    ],
  },
  {
    id: "summer-1",
    title: "Summer Real Estate Tower near Palace",
    city: "Addis Ababa",
    location: "Near New Grand Palace / Cabinet Project",
    price: 88000,
    beds: 2,
    baths: 2,
    area: 100,
    status: "For Sale",
    type: "Apartment",
    tags: ["luxury", "palace view", "bank loan", "summer real estate"],
    image: "1001616952_2.png",
    description:
      "Modern high-rise residential apartment by Summer Real Estate near the New Grand Palace. Features 50% bank loan financing support and panoramic views.",
    features: [
      "50% Bank Financing",
      "Prime Palace Neighborhood",
      "High-Rise Views",
      "88,000 ETB/m²",
    ],
  },
  {
    id: "summer-2",
    title: "Embassy View Apartment Unit",
    city: "Addis Ababa",
    location: "Near British Embassy",
    price: 78000,
    beds: 2,
    baths: 2,
    area: 138,
    status: "For Sale",
    type: "Apartment",
    tags: ["embassy area", "palace view", "high rental yield", "discount"],
    image: "1001616951_2.png",
    description:
      "High rental yield property near the British Embassy. Features 10% down payment options, 5% holiday discount, and handover in 27 months.",
    features: [
      "10% Down Payment",
      "5% Additional Discount",
      "Grand Palace View",
      "50% Bank Loan Approved",
    ],
  },
  {
    id: "summer-3",
    title: "Spacious Family Apartment near Embassy",
    city: "Addis Ababa",
    location: "Near British Embassy",
    price: 78000,
    beds: 3,
    baths: 2,
    area: 138,
    status: "For Sale",
    type: "Apartment",
    tags: ["family", "spacious", "british embassy", "holiday offer"],
    image: "1001616950_2.png",
    description:
      "Family apartments ranging from 2 to 4 bedrooms located near the British Embassy, featuring 50% bank loan approval and holiday pricing.",
    features: [
      "2 to 4 Bedroom Options",
      "50% Bank Financing",
      "5% Holiday Discount",
      "Delivery in 2 Years 3 Months",
    ],
  },
  {
    id: "summer-4",
    title: "Summer Real Estate Holiday Promo Unit",
    city: "Addis Ababa",
    location: "Near British Embassy",
    price: 78000,
    beds: 2,
    baths: 2,
    area: 120,
    status: "For Sale",
    type: "Apartment",
    tags: ["holiday discount", "investment", "british embassy"],
    image: "1001616949_2.png",
    description:
      "Special New Year / Holiday promotion offering up to 15% discount for apartments located near the British Embassy.",
    features: ["5% to 15% Discount", "78,000 ETB/m²", "Prime Diplomatic Area"],
  },
  {
    id: "eco-1",
    title: "Bole Atlas Riverside Shops & Apartments",
    city: "Addis Ababa",
    location: "Bole Atlas, 1.8km from Airport",
    price: 120000,
    beds: 2,
    baths: 2,
    area: 120,
    status: "For Sale",
    type: "Apartment",
    tags: ["bole atlas", "riverside", "airport vicinity", "commercial"],
    image: "1001616948.png",
    description:
      "Eco Real Estate presents Bole Atlas Riverside. Located just 1.8 km from Bole International Airport with a low 25% initial down payment.",
    features: [
      "25% Down Payment Only",
      "12% Grand Discount",
      "1.8 km to Airport",
      "Riverside Views",
    ],
  },
  {
    id: "eco-2",
    title: "Bole Atlas Commercial & Residential Units",
    city: "Addis Ababa",
    location: "Bole Atlas",
    price: 135000,
    beds: 3,
    baths: 3,
    area: 160,
    status: "For Sale",
    type: "Apartment",
    tags: ["bole atlas", "quick handover", "shops", "3 bed"],
    image: "1001616947.png",
    description:
      "Commercial shops starting from 15 m² (6-month handover) and spacious 3-bedroom luxury apartments starting from 160 m² (1-year handover).",
    features: [
      "Shops Handover in 6 Months",
      "Apartments Handover in 1 Year",
      "12% Discount Offer",
      "25% Down Payment",
    ],
  },
  {
    id: "eco-3",
    title: "Bole Atlas Luxury 3-Bedroom Units",
    city: "Addis Ababa",
    location: "Bole Atlas",
    price: 140000,
    beds: 3,
    baths: 3,
    area: 182,
    status: "For Sale",
    type: "Penthouse",
    tags: ["penthouse", "luxury", "bole atlas", "up to 18% discount"],
    image: "1001616946.png",
    description:
      "High-end 3-bedroom residences (160 m², 182 m², 190 m²) at Bole Atlas Riverside with discount promotions up to 18%.",
    features: [
      "Up to 18% Discount",
      "25% Down Payment",
      "Multiple Layout Configurations",
      "1-Year Guaranteed Handover",
    ],
  },
  {
    id: "eco-4",
    title: "Bole Atlas Retail Shop & Compact Unit",
    city: "Addis Ababa",
    location: "Bole Atlas",
    price: 150000,
    beds: 0,
    baths: 1,
    area: 15,
    status: "For Sale",
    type: "Commercial",
    tags: ["commercial", "shop", "bole atlas", "fast handover"],
    image: "1001616945.png",
    description:
      "Commercial shop units starting from 15 m² with short-term delivery options ranging between 6 to 12 months.",
    features: [
      "12% Promotional Discount",
      "Delivery in 6 to 12 Months",
      "Prime Bole Commercial Zone",
    ],
  },
];
